Treat generated AES key as an array
Netflix/dynomite pull request #536
Opened 2018-02-19 09:48 UTC by sobkovych

Due to a possibility of '\0' inside generated AES key we can't use "str-family" functions on key processing (e.g. strlen, strncpy etc.) and should treat key as an array. Otherwise, in some cases we get an error in dyn_aes_decrypt() routine ("Bad data in EVP_DecryptFinal_ex, crypto data with XX bytes of data").

2018-02-20 18:14 UTC, sobkovych commented
@shailesh33 
Hi, is there any chance to review this? Should the pull request be assigned to someone when creating?
Thanks!

2018-02-22 01:04 UTC, shailesh33 commented on src/dyn_connection_internal.c
> +        return NULL;
you should free conn here

2018-02-22 01:07 UTC, shailesh33 requested changes
Please fix that memory leak. Rest looks good to me

2018-02-22 08:46 UTC, sobkovych commented
@shailesh33 
Thanks, great! Fixed.

2018-03-14 11:31 UTC, sobkovych commented
@shailesh33 
Hi, is there any chance to finish with this PR?

2018-03-14 16:38 UTC, shailesh33 commented on src/dyn_connection_internal.c
> +        dn_free(conn);
I am not exactly sure but may be you should use _conn_put() here. Infact may be generate the aes key at the beginning of the function and fail right there.

2018-03-14 16:39 UTC, shailesh33 approved these changes
it will be great if you can do those changes. I am approving nevertheless.

2018-03-15 15:36 UTC, sobkovych commented
Yes, you're absolutely right! Done, please take a look.
Thanks!

2018-03-15 16:09 UTC, shailesh33 approved these changes

2018-03-15 16:09 UTC, merged